name: "opd-professional-score"
services:
  frontend:
    container_name: frontend
    image: node:23
    ports:
      - "8070:8070"
    entrypoint: /bin/bash /home/startup.sh
    volumes:
      - ./node:/home/